
### course create
POST localhost:8080/course/create
Content-Type: application/json

{
  "name": "Java",
  "price": 100000,
  "duration": "7 oy"
}

### getById
GET localhost:8080/course/getById/1
Content-Type: application/json

### getList
GET localhost:8080/course/getList
Content-Type: application/json

### update
PUT localhost:8080/course/update/3
Content-Type: application/json

{
  "name": "Ruby",
  "price": 500000,
  "duration": "7 oy"
}

### delete
DELETE localhost:8080/course/delete/3
Content-Type: application/json

### getByName
GET localhost:8080/course/getByName/Java
Content-Type: application/json

### getByPrice
GET localhost:8080/course/getByPrice/1200000.0
Content-Type: application/json

### getCreateDate
GET localhost:8080/course/getByCreateDateBetween?fromDate=2023-04-05T14:28:42.775214&toDate=2023-04-05T14:51:41.32928
Content-Type: application/json